version: '3'
services:
    prometheus:
        image: prom/prometheus:v2.20.1
        ports: 
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
        image: grafana/grafana:8.0.6
        ports:
        - "3000:3000"
        environment:
            GF_AUTH_DISABLE_LOGIN_FORM: 'true'
            GF_AUTH_ANONYMOUS_ENABLED: 'true'
            GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
        volumes: 
            - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
            - grafana-lib:/var/lib/grafana
            - grafana-etc:/etc/grafana

volumes: 
    grafana-etc:
    grafana-lib: